name: CD
on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 #チェックアウトするアクション
      - name: Use NodeJS
        uses: actions/setup-node@v3 #特定バージョンのnodeを設定するアクション
        with:
          node-version: 16
      - run: npm run predeploy #dependencyのインストール
      - run: npm run format:check #コードフォーマットチェック
      - run: npm run deploy